version: "3.4"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../src/:/var/www
    restart: always

 # database:
 #   container_name: database
 #   image: postgres:${POSTGRES_VERSION:-13}-alpine
 #   environment:
 #     POSTGRES_DB: ${POSTGRES_DB:-app}
 #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
 #     POSTGRES_USER: ${POSTGRES_USER:-symfony}
 #   volumes:
 #     - db_data:/var/lib/postgresql/data:rw

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ADMINER_DEFAULT_USER: ${POSTGRES_USER:-symfony}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-app}
  exit:
    image: 'postgres:alpine'
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - '5432'



###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
volumes:
  php_socket:
  caddy_data:
  ###> doctrine/doctrine-bundle ###
  db_data:
  ###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
