version: "3.4"

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./php
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../src/:/var/www



  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db_data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      ADMINER_DEFAULT_USER: ${POSTGRES_USER:-symfony}
      ADMINER_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      ADMINER_DEFAULT_TYPE: postgresql
      ADMINER_DEFAULT_PORT: 5432
      ADMINER_DEFAULT_DB: ${POSTGRES_DB:-app}



###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
volumes:
  php_socket:
  caddy_data:
  ###> doctrine/doctrine-bundle ###
  db_data:
  ###< doctrine/doctrine-bundle ###
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
